name: multi_sensor_dropout
channels:
  - defaults
dependencies:
  - python=3.11
  - conda-forge::einops
  - conda-forge::tqdm
  - conda-forge::torchmetrics
  - conda-forge::scipy
  - conda-forge::wandb
