name: multi_sensor_dropout
channels:
  - defaults
dependencies:
  - python=3.11
  - conda-forge::einops
  - conda-forge::tqdm
  - conda-forge::torchmetrics
  - conda-forge::scipy
  - conda-forge::wandb
  - conda-forge::datasets
  - conda-forge::ultralytics
  - conda-forge::transformers
  - pip:
      - detection-moving-mnist==0.4.3
      - fiftyone==0.1.0
      - tidecv==0.1.0
      - motmetrics=1.4.0